Repository My-Pack/MyPack-Web, pull requests merged in 2023-06, with the labels that each got.

#73 [#31] 메인페이지
  src/components/Card/Btn.tsx
  src/components/Card/CardEffectItem.tsx
  src/components/Card/Design/FormBgcolor.tsx
  src/components/Card/Design/FormTitle.tsx
  src/components/Card/Design/PreviewCard.tsx
  src/components/Card/index.tsx
  src/components/CardList/index.tsx
  src/components/Main/Footer/index.tsx
  src/components/Main/SectionTitle.tsx
  src/pages/DesignCard/index.tsx
  src/pages/index.tsx
Labels: feat, style

#74 [#68] 카드 이미지 저장하기 기능
  package-lock.json
  package.json
  src/components/Card/index.tsx
  src/components/CardList/index.tsx
  src/pages/index.tsx
Labels: feat

#78 [none] 삭제 수정 , 카드리스트 제한 수정
  src/components/CardList/index.tsx
  src/pages/Detail/[cardId].tsx
Labels: fix

#81 [#77] 돋보기 detail api, introduce page
  src/@types/card.d.ts
  src/components/Card/Btn.tsx
  src/components/Card/CardEffectItem.tsx
  src/components/Card/Design/PreviewCard.tsx
  src/components/Card/index.tsx
  src/components/CardList/index.tsx
  src/components/Introduce/Section/CardDesign/index.tsx
  src/components/Introduce/Section/CardIntroduction/index.tsx
  src/components/Nav/Hamburger/index.tsx
  src/hooks/api/useComment.ts
  src/hooks/api/useGetCard.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/server.ts
  src/mocks/worker.ts
  src/pages/DesignCard/index.tsx
  src/pages/Detail/[cardId].tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/profile/index.tsx
Labels: feat, style

#82 [none]fix: myprofile 수정
  src/pages/profile/index.tsx
Labels: feat
