Repository My-Pack/MyPack-Web, pull requests merged in 2023-03, with the labels that each got.

#2 [#1] 개발 환경 설정
  .github/.gitmessage
  .github/auto_assign.yml
  package-lock.json
  package.json
Labels: env

#5 [#3] 테스팅 환경 설정
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/pages/index.tsx
  tests/index/__snapshots__/index.test.tsx.snap
  tests/index/index.test.tsx
  tsconfig.json
Labels: feat

#9 [#8] logo 적용
  public/assets/images/logo.png
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: env, feat

#7 [#6] login page
  package-lock.json
  package.json
  public/assets/images/appstore.png
  public/assets/images/google_btn.png
  src/pages/_app.tsx
  src/pages/login/index.tsx
  styles/GlobalStyle.tsx
  styles/Theme/theme.ts
  tsconfig.json
Labels: feat
