Repository My-Pack/MyPack-Web, pull requests merged in 2023-04, with the labels that each got.

#16 [#15] style 설정 및 styled-components 세팅
  package-lock.json
  package.json
  src/@types/styled.d.ts
  styles/GlobalStyle.tsx
  styles/Theme/theme.ts
Labels: feat, style

#17 [#12] Hamberger 컴포넌트
  next.config.js
  src/components/Hamburger/index.tsx
  src/pages/index.tsx
  styles/Theme/theme.ts
  tests/index/Hamburger.test.js
  tests/index/index.test.tsx
  tsconfig.json
Labels: feat

#21 [#11] 로그인 레이아웃 수정
  public/assets/images/account_clay.png
  src/pages/login/index.tsx
  styles/Theme/theme.ts
Labels: fix

#23 [#18] 카드 컴포넌트 개발
  package-lock.json
  package.json
  src/components/Card/CardBack.tsx
  src/components/Card/CardEffectItem.tsx
  src/components/Card/CardItem.tsx
  src/constants/motion.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
Labels: feat

#25 [#24] login test코드 작성
  tests/index/Hamburger.test.js
  tests/index/login.test.tsx
Labels: test

#28 [#26] 모바일 환경
  public/assets/images/appStore.svg
  src/components/DeviceWarning.tsx
  src/hooks/useMediaQuery.ts
  src/pages/_app.tsx
Labels: feat

#29 [#11] 로그인 개선
  .gitignore
  package-lock.json
  package.json
  public/assets/images/accountClay.png
  public/assets/images/appleLogin.png
  public/assets/images/google_btn.png
  src/components/LoginBack/index.tsx
  src/pages/login/index.tsx
Labels: fix

#33 [#22] DragAndDrop
  package-lock.json
  package.json
  src/components/DragAndDrop/index.tsx
  src/pages/DragAndDrop/index.tsx
  src/pages/_app.tsx
  tests/index/__snapshots__/hamberger.test.tsx.snap
  tests/index/hamberger.test.tsx
Labels: feat

#34 [#10] 검색창
  package-lock.json
  package.json
  src/@types/member.d.ts
  src/@types/pageable.d.ts
  src/@types/sort.d.ts
  src/components/Nav/Hamburger/index.tsx
  src/components/Nav/index.tsx
  src/components/Search/index.tsx
  src/constants/motion.ts
  src/libs/api/api.ts
  src/pages/index.tsx
Labels: feat

#39 [#36] 로그인 백 통신
  package-lock.json
  src/pages/login/index.tsx
  tests/index/__snapshots__/hamberger.test.tsx.snap
  tests/index/hamberger.test.tsx
  tests/index/login.test.tsx
Labels: feat

#41 [#37] swiper 추가
  package-lock.json
  package.json
  src/components/CardList/index.tsx
  src/components/CardList/styles.css
  tests/index/login.test.tsx
Labels: feat

#42 [#35] 서비스 소개 페이지
  package-lock.json
  package.json
  public/assets/images/appStore.svg
  public/assets/images/appleLogo.png
  public/assets/images/appstore.png
  public/assets/images/card.png
  public/assets/images/cardDragItem1.jpeg
  public/assets/images/cardDragItem2.png
  public/assets/images/cardItem.png
  src/assets/lottieJSON/arrowDown.json
  src/assets/lottieJSON/cardPack.json
  src/assets/lottieJSON/cursor.json
  src/assets/lottieJSON/custom.json
  src/assets/lottieJSON/globe.json
  src/assets/lottieJSON/heart.json
  src/assets/lottieJSON/search.json
  src/components/Card/CardEffectItem.tsx
  src/components/Common/DragItem/Img.tsx
  src/components/Common/DragItem/Text.tsx
  src/components/Common/DragItem/index.tsx
  src/components/Common/LottieWrapper.tsx
  src/components/Introduce/Button/index.tsx
  src/components/Introduce/Card/CardPack/index.tsx
  src/components/Introduce/Card/Custom/index.tsx
  src/components/Introduce/Card/Record/index.tsx
  src/components/Introduce/Card/Share/index.tsx
  src/components/Introduce/Card/World/index.tsx
  src/components/Introduce/Card/index.tsx
  src/components/Introduce/Section/CardComposition/index.tsx
  src/components/Introduce/Section/CardDesign/index.tsx
  src/components/Introduce/Section/CardIntroduction/index.tsx
  src/components/Introduce/Section/Outro/index.tsx
  src/components/Introduce/SectionTitle.tsx
  src/pages/_app.tsx
  src/pages/introduce/index.tsx
  styles/GlobalStyle.tsx
  styles/Theme/theme.ts
Labels: feat, style
