Repository My-Pack/MyPack-Web, pull requests merged in 2023-05, with the labels that each got.

#46 [#45] github action 적용
  .github/workflows/ci.yml
  src/components/Card/CardEffectItem.tsx
Labels: feat

#52 [#50] msw
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/server.ts
  src/mocks/worker.ts
  src/pages/_app.tsx
Labels: feat

#47 [#43] 404 Page
  src/assets/lottieJSON/notFound.json
  src/components/CardList/styles.css
  src/pages/404/index.tsx
Labels: feat

#54 [#53] 멋진 글씨
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/utils/gradient.ts
Labels: style

#56 [#48] 로그인 로직 분리
  src/hooks/api/onHandleGoogleLogin.ts
  src/pages/login/index.tsx
Labels: fix

#59 [#55] profile page
  next.config.js
  package-lock.json
  package.json
  src/@types/profile.d.ts
  src/assets/lottieJSON/loading.json
  src/components/Loading/index.tsx
  src/components/Profile/CardList/Card.tsx
  src/components/Profile/CardList/ProfileCardList.tsx
  src/components/Profile/Info.tsx
  src/mocks/handlers.ts
  src/pages/profile/index.tsx
  styles/Theme/theme.ts
Labels: feat

#67 [#66] 커스텀 방법 설명
  src/components/Card/Design/HowTo.tsx
  src/constants/howto.ts
  src/pages/DesignCard/index.tsx
Labels: feat, style

#69 [#62] 카드 디테일 페이지
  package-lock.json
  package.json
  src/@types/comment.d.ts
  src/components/Card/CardEffectItem.tsx
  src/components/Card/Design/FormBgcolor.tsx
  src/components/Card/index.tsx
  src/components/Nav/index.tsx
  src/hooks/api/useComment.ts
  src/hooks/useTextArea.ts
  src/pages/Detail/[cardId].tsx
  src/pages/index.tsx
Labels: feat, style

#71 [#70] 네브바
  src/@types/profile.d.ts
  src/components/Card/Design/HowTo.tsx
  src/components/Nav/Hamburger/index.tsx
  src/pages/DesignCard/index.tsx
  src/pages/profile/index.tsx
Labels: feat, style

#72 SinglePageLikeList 컴포넌트
  next.config.js
  src/@types/card.d.ts
  src/components/SinglePageLikeList/index.tsx
  src/hooks/useModal.ts
  src/pages/Detail/[cardId].tsx
  src/pages/profile/edit/index.tsx
  styles/Theme/theme.ts
Labels: feat
